swagger: "2.0"
info:
  description: " Swagger at [http://swagger.io](http://swagger.io) API for Inventar Microservice"
  version: "0.0.1"
  title: "Inventar Microservice"
  
host: "inventar.spirit-testing.de"
basePath: "/api"


paths:
  /inventar/{inventarId}:
    get:
      tags:
      - "inventarverwaltung"
      summary: "Find inventar item by ID"
      description: "Returns a single inventar item"
      operationId: "getPetById"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "inventarId"
        in: "path"
        description: "ID of pet to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Asset"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Pet not found"
    
      
definitions:
  Asset:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      inventarId:
        type: "integer"
        format: "int64"
      uebergabeDatum:
        type: "string"
        format: "date-time"
      uebergabeZustand:
        type: "string"
        description: "Zustand des Items bei Uebergabe"
        enum:
          - "tadellos"
          - "leichte gebrauchsspuren"
          - "starke gebrauchsspuren"
          - "beschädigt"
          - "defekt"
        